dist: trusty
sudo: false
language: c
os:
  - linux
compiler: gcc-5
env:
  global:
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    #
    # GH_TOKEN: Marvim's Github access token
    - secure: N73UKR9bIcAh5q+YXdru8iWdMJh6V85PMtl14ZK4EzTi1MP8AcSuTEJMOAizGOcYL+jL7tM/Kd8rxsJVYcwdqIPij4jugNsm4UZLgxAoI1rZ2wpUHAqQdknTFGzss64UuNehbcEM82aK5/qbtvzU3eM8UVVVsuTg8SvB+XAmdI4=
    # COVERITY_SCAN_TOKEN
    - secure: DlaBxxav917aS8n/NU1K1wJirSDWssret2F2BBZRnUMWDJTRgL+j2e89k67446sW63x/T0gbvlPKo6hoKS5s7C4jEq+t6aKtbOhSLsE8A36++19SvZEC0Tagll1ho6ozA6Tal3WHs6NnW198tpFEkKOoD5qrfa+E/onVKjtT+iE=
  matrix:
    - CI_TARGET=assign-labels
    - CI_TARGET=deps-src
    - CI_TARGET=doc-index
    - CI_TARGET=doxygen
    - CI_TARGET=nightly
    - CI_TARGET=sync-mirrors
    - CI_TARGET=sync-lp-mirrors
    - CI_TARGET=translation-report
    - CI_TARGET=user-docu
    - CI_TARGET=vimpatch-report
    - CI_TARGET=clint-errors
    - CI_TARGET=pvs-report
matrix:
  include:
    - os: linux
      env: CI_TARGET=clang-report SCAN_BUILD=scan-build-3.9
      compiler: clang-3.9
    - os: osx
      env: CI_TARGET=nightly
      compiler: clang
#    - os: linux
#      env: CI_TARGET=coverity
#  allow_failures:
#    - os: linux
#      env: CI_TARGET=coverity
install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install bash;
      brew install jq;
      brew install gettext;
      brew reinstall -s libtool;
    fi
script:
  - ./ci/${CI_TARGET}.sh
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - build-essential
      - bzr-fastimport
      - clang-3.9
      - cmake
      - g++-5
      - gcc-5
      - gdb
      - libtool
      - llvm-3.9-dev
      - pkg-config
      - unzip
      - xclip
cache:
  apt: true
  directories:
    - "${TRAVIS_BUILD_DIR}/.deps/build/src"

notifications:
  email:
    on_success: never
